#!/usr/bin/env python3
"""
Script to plot the flight envelope from vmax_analysis.csv
Generated by AnalyseurEnveloppeVol::analyser_limites_vitesse()

The flight envelope shows:
- Upper boundary: Maximum speed (thrust/structural limit)
- Lower boundary: Minimum speed (stall limit)
- Shaded area: Safe flight regime
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sys
import os

def plot_envelope(csv_file='vmax_analysis.csv'):
    """Plot the flight envelope from CSV data."""
    
    # Check if file exists
    if not os.path.exists(csv_file):
        print(f"Error: {csv_file} not found!")
        print("Run the C++ simulation with AnalyseurEnveloppeVol first.")
        sys.exit(1)
    
    # Read CSV data
    df = pd.read_csv(csv_file)
    
    # Extract data
    altitude = df['altitude'].values
    v_max = df['v_max_m_s'].values
    v_min = df['v_min'].values
    mach_max = df['Mach_max'].values
    mach_min = df['Mach_min'].values
    
    # Check if stability criterion column exists
    has_stability = 'stability_criterion' in df.columns
    if has_stability:
        stability_crit = df['stability_criterion'].values
    
    # Convert altitude to kilometers for cleaner plots
    altitude_km = altitude / 1000.0
    
    # Create figure with two subplots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 8))
    
    # ============ Plot 1: Velocity vs Altitude ============
    ax1.plot(v_min, altitude_km, 'r-', linewidth=2.5, label='Stall Speed (V_min)', marker='o')
    ax1.plot(v_max, altitude_km, 'b-', linewidth=2.5, label='Max Speed (V_max - Stability limit)', marker='s')
    
    # Fill the safe flight envelope
    ax1.fill_betweenx(altitude_km, v_min, v_max, alpha=0.3, color='green', label='Flight Envelope')
    
    # Mark coffin corner region (where V_min approaches V_max)
    speed_margin = v_max - v_min
    dangerous_mask = speed_margin < 50.0  # Less than 50 m/s margin
    if np.any(dangerous_mask):
        dangerous_alts = altitude_km[dangerous_mask]
        ax1.axhspan(dangerous_alts.min(), dangerous_alts.max(), 
                   alpha=0.2, color='orange', label='Coffin Corner (narrow margin)')
    
    # Add reference speeds
    ax1.axvline(230, color='gray', linestyle='--', alpha=0.5, label='Cruise Speed (230 m/s)')
    
    ax1.set_xlabel('Airspeed (m/s)', fontsize=12, fontweight='bold')
    ax1.set_ylabel('Altitude (km)', fontsize=12, fontweight='bold')
    ax1.set_title('Flight Envelope - True Airspeed', fontsize=14, fontweight='bold')
    ax1.grid(True, alpha=0.3)
    ax1.legend(loc='best', fontsize=10)
    ax1.set_xlim(0, max(v_max) * 1.1)
    ax1.set_ylim(0, max(altitude_km) * 1.1)
    
    # ============ Plot 2: Mach Number vs Altitude ============
    ax2.plot(mach_min, altitude_km, 'r-', linewidth=2.5, label='Stall Mach (M_min)', marker='o')
    ax2.plot(mach_max, altitude_km, 'b-', linewidth=2.5, label='Max Mach (M_max - Stability limit)', marker='s')
    
    # Fill the safe flight envelope
    ax2.fill_betweenx(altitude_km, mach_min, mach_max, alpha=0.3, color='green', label='Flight Envelope')
    
    # Mark coffin corner region
    if np.any(dangerous_mask):
        ax2.axhspan(dangerous_alts.min(), dangerous_alts.max(), 
                   alpha=0.2, color='orange', label='Coffin Corner')
    
    # Add reference Mach numbers
    ax2.axvline(0.82, color='gray', linestyle='--', alpha=0.5, label='MMO (M=0.82)')
    ax2.axvline(0.3, color='orange', linestyle=':', alpha=0.5, label='Compressibility onset')
    
    ax2.set_xlabel('Mach Number', fontsize=12, fontweight='bold')
    ax2.set_ylabel('Altitude (km)', fontsize=12, fontweight='bold')
    ax2.set_title('Flight Envelope - Mach Number', fontsize=14, fontweight='bold')
    ax2.grid(True, alpha=0.3)
    ax2.legend(loc='best', fontsize=10)
    ax2.set_xlim(0, max(mach_max) * 1.1)
    ax2.set_ylim(0, max(altitude_km) * 1.1)
    
    plt.tight_layout()
    
    # Save figure
    plt.savefig('flight_envelope.png', dpi=300, bbox_inches='tight')
    print(f"✓ Flight envelope plot saved as 'flight_envelope.png'")
    
    plt.show()
    
    # Print summary statistics
    print("\n" + "="*60)
    print("FLIGHT ENVELOPE SUMMARY")
    print("="*60)
    
    for i in range(len(altitude)):
        alt_km = altitude[i] / 1000.0
        print(f"\nAltitude: {alt_km:5.1f} km")
        print(f"  V_min = {v_min[i]:6.1f} m/s  (M = {mach_min[i]:.3f})")
        print(f"  V_max = {v_max[i]:6.1f} m/s  (M = {mach_max[i]:.3f})")
        print(f"  Speed range: {v_max[i] - v_min[i]:6.1f} m/s")
        if has_stability:
            print(f"  Limiting criterion: {stability_crit[i]}")
    
    # Find optimal cruise altitude (largest speed range)
    speed_range = v_max - v_min
    optimal_idx = np.argmax(speed_range)
    print("\n" + "="*60)
    print(f"OPTIMAL CRUISE ALTITUDE: {altitude[optimal_idx]/1000:.1f} km")
    print(f"  Speed range: {speed_range[optimal_idx]:.1f} m/s")
    print(f"  ({v_min[optimal_idx]:.1f} - {v_max[optimal_idx]:.1f} m/s)")
    print("="*60)


if __name__ == "__main__":
    # Allow custom CSV file path
    csv_file = sys.argv[1] if len(sys.argv) > 1 else 'vmax_analysis.csv'
    plot_envelope(csv_file)
